### ISSUE TITLE
安装数据库后 启动异常

### ISSUE THREAD

**Issue by edenleung** [walkor/webman#117]
按照文档安装以下组件, 进行试用数据库。

```
    "vlucas/phpdotenv": "5.1.0",
    "illuminate/database": "^7.30"
```

启动服务后 出现以下异常。

```
Fatal error: Uncaught Error: Call to private Dotenv\Repository\Adapter\EnvConstAdapter::__construct() from context 'Illuminate\Support\Env' in C:\dnmp\www\webman\vendor\illuminate\support\Env.php:58
Stack trace:
#0 C:\dnmp\www\webman\vendor\illuminate\support\Env.php(81): Illuminate\Support\Env::getRepository()
#1 C:\dnmp\www\webman\vendor\illuminate\support\helpers.php(276): Illuminate\Support\Env::get('APP_DEBUG', false)
#2 C:\dnmp\www\webman\config\app.php(16): env('APP_DEBUG', false)
#3 C:\dnmp\www\webman\vendor\workerman\webman-framework\src\Config.php(36): include('C:\\dnmp\\www\\web...')
#4 C:\dnmp\www\webman\start.php(22): Webman\Config::load('C:\\dnmp\\www\\web...', Array)
#5 {main}
  thrown in C:\dnmp\www\webman\vendor\illuminate\support\Env.php on line 58
```

PHP 版本
```
PHP 7.2.19 (cli) (built: May 29 2019 13:58:59) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

我需要怎么处理这个异常。

**Comment by walkor** [comment]
"vlucas/phpdotenv": "5.x" 用 illuminate/database 8.x 。
如果你要用 "illuminate/database": "7.x"，使用"vlucas/phpdotenv": "4.x" 

执行 `composer require vlucas/phpdotenv ^4.0` 试下。

**Comment by edenleung** [comment]
上面的方法有效，解决了。
