### ISSUE TITLE
使用 aop 报错

### ISSUE THREAD

**Issue by teg1c** [walkor/webman#180]
```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Hyperf\Utils\Filesystem\Filesystem::lastModified() must be of the type string, bool given, called in /Users/mac/Documents/www/webman/vendor/hyperf/di/src/Annotation/Scanner.php on line 341 and defined in /Users/mac/Documents/www/webman/vendor/hyperf/utils/src/Filesystem/Filesystem.php:306
Stack trace:
#0 /Users/mac/Documents/www/webman/vendor/hyperf/di/src/Annotation/Scanner.php(341): Hyperf\Utils\Filesystem\Filesystem->lastModified(false)
#1 /Users/mac/Documents/www/webman/vendor/hyperf/di/src/Annotation/Scanner.php(266): Hyperf\Di\Annotation\Scanner->getChangedAspects(Array, 0)
#2 /Users/mac/Documents/www/webman/vendor/hyperf/di/src/Annotation/Scanner.php(146): Hyperf\Di\Annotation\Scanner->loadAspects(0)
#3 /Users/mac/Documents/www/webman/vendor/hyperf/di/src/ClassLoader.php(50): Hyperf\Di\Annotation\Scanner->scan()
#4 /Users/mac/Documents/www/webman/vendor/hyperf/di/src/ClassLoader.php(89): Hyperf\Di\ClassLoader->__construct(Object(Composer\Autoload\ClassLoader), ' in /Users/mac/Documents/www/webman/vendor/hyperf/utils/src/Filesystem/Filesystem.php on line 306

```

文档里用的是 hyperf 的 `hyperf/aop-integration` 
这个组件在启动是时候会扫描 `psr-4` 加载的相关文件,启动会加载`Hyperf\Config\ProviderConfig`这个类,但是 aop 组建并不会自动安装 hyperf 的 `hyperf/config` 组建,导致
`vendor/hyperf/di/src/Annotation/Scanner.php`
这个文件的 `339` 行去加载 `Hyperf\Config\ProviderConfig` class的时候找不到会直接返回 `false` 
```
if ($lastCacheModified <= $this->filesystem->lastModified($file)) {
                $changed[] = $class;
            }
```
这里 `lastModified` 方法传进去的`$file` 其实是 `false`,会报强类型错误

```
public function lastModified(string $path): int
    {
        return filemtime($path);
    }
```

**Comment by teg1c** [comment]
其实在组建内加一层判断就可以解决
```
if ($file && $lastCacheModified <= $this->filesystem->lastModified($file)) {
                $changed[] = $class;
            }
```

但是明显修改 hyperf 的组建不太好

**Comment by walkor** [comment]
aop这个我没有研究过，文档当时是 hyperf 团队提交的。如果加一层判断就可以解决，欢迎给 hyperf 发个pr，一起完善aop。

**Comment by qq781548819** [comment]
Fatal error: Declaration of Hyperf\AopIntegration\ClassLoader::init(?string $proxyFileDirPath = null, ?string $configDir = null): void must be compatible with Hyperf\Di\ClassLoader::init(?string $proxyFileDirPath = null, ?string $configDir = null, ?Hyperf\Di\ScanHandler\ScanHandlerInterface $handler = null): void in D:\Phpcode\webman-admin\vendor\hyperf\aop-integration\src\ClassLoader.php on line 22
按文档使用hyperf出现这个异常。
