### ISSUE TITLE
Customize workerman usage

### ISSUE THREAD

**Issue by cayolblake** [walkor/webman#291]
Hello @walkor 

How to customize `workerman` usage? Like set the number of processes and the eventloop ..etc. ?

**Comment by cayolblake** [comment]
Just found `config/server.php` to control number of processes. Not sure if event loop could be modified there as well.

**Comment by walkor** [comment]
webman not support customize  event loop. May be next version support that.

**Comment by accuretix** [comment]
Hi @walkor 

Is it possible now to switch Webman to another event loop, for example Swoole?

**Comment by accuretix** [comment]
Okay, apparently I can from config/server.php file, however with Swoole v5 (not OpenSwoole) I am getting...

```
------------------------------------------- WORKERMAN --------------------------------------------
Workerman version:4.1.13          PHP version:8.2.9           Event-Loop:Workerman\Events\Swoole
-------------------------------------------- WORKERS ---------------------------------------------
proto   user            worker          listen                 processes    status
tcp     drvsh           webman          http://0.0.0.0:8787    16            [OK]
tcp     drvsh           monitor         none                   1             [OK]
--------------------------------------------------------------------------------------------------
Press Ctrl+C to stop. Start success.
PHP Fatal error:  Uncaught Error: Class "Swoole\Timer" not found in ~/webman/vendor/workerman/workerman/Events/Swoole.php:48
Stack trace:
#0~/webman/vendor/workerman/workerman/Worker.php(1195): Workerman\Events\Swoole->add()
#1 ~/webman/vendor/workerman/workerman/Worker.php(1623): Workerman\Worker::reinstallSignal()
#2 ~/webman/vendor/workerman/workerman/Worker.php(1426): Workerman\Worker::forkOneWorkerForLinux()
#3 ~/webman/vendor/workerman/workerman/Worker.php(1400): Workerman\Worker::forkWorkersForLinux()
#4 ~/webman/vendor/workerman/workerman/Worker.php(560): Workerman\Worker::forkWorkers()
#5 ~/webman/vendor/workerman/webman-framework/src/support/App.php(131): Workerman\Worker::runAll()
#6 ~/webman/start.php(4): support\App::run()
#7 {main}
  thrown in ~/webman/vendor/workerman/workerman/Events/Swoole.php on line 48
```
