### ISSUE TITLE
一般什么情况下会出现fullUrl获取为空的情况？

### ISSUE THREAD

**Issue by wolf-leo** [walkor/webman#301]
> 以下是记录的日志；

```
访问地址: http:///favicon.ico
[0]
IP地址: 109.248.6.123
错误信息: ErrorException in
   /path/vendor/workerman/workerman/Protocols/Http/Request.php
   line 227
   strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated
```

> 异常信息：

```
#1 /path/vendor/workerman/workerman/Protocols/Http/Request.php(227): strpos()
#2 /path/app/middleware/CheckIndex.php(14): Workerman\Protocols\Http\Request->host()
#3 /path/vendor/workerman/webman-framework/src/App.php(227): app\middleware\CheckIndex->process()
#4 /path/vendor/workerman/webman-framework/src/App.php(136): Webman\App::Webman\{closure}()
#5 /path/vendor/workerman/workerman/Connection/TcpConnection.php(638): Webman\App->onMessage()
#6 [internal function]: Workerman\Connection\TcpConnection->baseRead()
#7 /path/vendor/workerman/workerman/Events/Event.php(193): EventBase->loop()
#8 /path/vendor/workerman/workerman/Worker.php(2431): Workerman\Events\Event->loop()
#9 /path/vendor/workerman/workerman/Worker.php(1555): Workerman\Worker->run()
#10 /path/vendor/workerman/workerman/Worker.php(1397): Workerman\Worker::forkOneWorkerForLinux()
#11 /path/vendor/workerman/workerman/Worker.php(1371): Workerman\Worker::forkWorkersForLinux()
#12 /path/vendor/workerman/workerman/Worker.php(1692): Workerman\Worker::forkWorkers()
#13 /path/vendor/workerman/workerman/Worker.php(1641): Workerman\Worker::monitorWorkersForLinux()
#14 /path/vendor/workerman/workerman/Worker.php(551): Workerman\Worker::monitorWorkers()
#15 /path/start.php(94): Workerman\Worker::runAll()
#16 {main} [] []
```

**Comment by walkor** [comment]
/path/vendor/workerman/workerman/Protocols/Http/Request.php
if里加一个 `$host && `
```
        if ($host && $without_port && $pos = \strpos($host, ':')) {
            return \substr($host, 0, $pos);
        }
```

**Comment by wolf-leo** [comment]
> /path/vendor/workerman/workerman/Protocols/Http/Request.php if里加一个 `$host && `
> 
> ```
>         if ($host && $without_port && $pos = \strpos($host, ':')) {
>             return \substr($host, 0, $pos);
>         }
> ```
> 
> 你先本地改下试下是否ok，ok的话后面发个版本修复这个问题。

好的👌
