### ISSUE TITLE
Error after add composer require illuminate/database

### ISSUE THREAD

**Issue by haidarvm** [walkor/webman#33]
```
#9 {main}
Error: Class 'Illuminate\Events\Dispatcher' not found in /home/haidar/public_html/test/bench/webman/support/bootstrap/db/Laravel.php:47
Stack trace:
#0 /home/haidar/public_html/test/bench/webman/start.php(59): support\bootstrap\db\Laravel::start()
#1 /home/haidar/public_html/test/bench/webman/vendor/workerman/workerman/Worker.php(2397): {closure}()
#2 /home/haidar/public_html/test/bench/webman/vendor/workerman/workerman/Worker.php(1537): Workerman\Worker->run()
#3 /home/haidar/public_html/test/bench/webman/vendor/workerman/workerman/Worker.php(1367): Workerman\Worker::forkOneWorkerForLinux()
#4 /home/haidar/public_html/test/bench/webman/vendor/workerman/workerman/Worker.php(1341): Workerman\Worker::forkWorkersForLinux()
#5 /home/haidar/public_html/test/bench/webman/vendor/workerman/workerman/Worker.php(1674): Workerman\Worker::forkWorkers()
#6 /home/haidar/public_html/test/bench/webman/vendor/workerman/workerman/Worker.php(1623): Workerman\Worker::monitorWorkersForLinux()
#7 /home/haidar/public_html/test/bench/webman/vendor/workerman/workerman/Worker.php(544): Workerman\Worker::monitorWorkers()
#8 /home/haidar/public_html/test/bench/webman/start.php(130): Workerman\Worker::runAll()
```

The composer setting is
```
"require": {
        "php": ">=7.2",
        "workerman/webman-framework": "^1.0",
        "monolog/monolog": "^2.0",
        "vlucas/phpdotenv": "^5.1",
        "illuminate/database": "^8.0"
    },
```
How to fix it ?

**Comment by walkor** [comment]
Update webman or run command `composer require illuminate/events`.

**Comment by haidarvm** [comment]
Ok, now works perfectly, thanks
