### ISSUE TITLE
MongoDb的驱动能否修改最新的？

### ISSUE THREAD

**Issue by sanergogogo** [walkor/webman#398]
当前MongoDb使用的是jenssegers/mongodb 而且好想没维护了
最新的是mongodb/laravel-mongodb 这个功能比较完善

**Comment by walkor** [comment]
现在支持mongodb/laravel-mongodb&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sanergogogo ***@***.***&gt;
发送时间: 2024年1月19日 19:57
收件人: walkor/webman ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [walkor/webman] MongoDb的驱动能否修改最新的？ (Issue #398)





 
当前MongoDb使用的是jenssegers/mongodb 而且好想没维护了
 最新的是mongodb/laravel-mongodb 这个功能比较完善

**Comment by sanergogogo** [comment]
好的。看到了3个月前已经更新了

**Comment by hsSam** [comment]
Error: Class "Jenssegers\Mongodb\Connection" not found in /home/ubuntu/webman/webman/vendor/workerman/webman-framework/src/support/bootstrap/LaravelDb.php:61
Stack trace:
#0 [internal function]: support\bootstrap\LaravelDb::support\bootstrap\{closure}()
#1 /home/ubuntu/webman/webman/vendor/illuminate/database/DatabaseManager.php(157): call_user_func()
#2 /home/ubuntu/webman/webman/vendor/illuminate/database/DatabaseManager.php(93): Illuminate\Database\DatabaseManager->makeConnection()
#3 /home/ubuntu/webman/webman/vendor/illuminate/database/Capsule/Manager.php(109): Illuminate\Database\DatabaseManager->connection()
#4 /home/ubuntu/webman/webman/vendor/illuminate/database/Capsule/Manager.php(74): Illuminate\Database\Capsule\Manager->getConnection()
#5 /home/ubuntu/webman/webman/app/controller/IndexController.php(28): Illuminate\Database\Capsule\Manager::connection()
#6 /home/ubuntu/webman/webman/vendor/workerman/webman-framework/src/App.php(319): app\controller\IndexController->view()
#7 /home/ubuntu/webman/webman/vendor/workerman/webman-framework/src/App.php(141): Webman\App::Webman\{closure}()
#8 /home/ubuntu/webman/webman/vendor/workerman/workerman/Connection/TcpConnection.php(646): Webman\App->onMessage()
#9 [internal function]: Workerman\Connection\TcpConnection->baseRead()
#10 /home/ubuntu/webman/webman/vendor/workerman/workerman/Events/Event.php(193): EventBase->loop()
#11 /home/ubuntu/webman/webman/vendor/workerman/workerman/Worker.php(1638): Workerman\Events\Event->loop()
#12 /home/ubuntu/webman/webman/vendor/workerman/workerman/Worker.php(1429): Workerman\Worker::forkOneWorkerForLinux()
#13 /home/ubuntu/webman/webman/vendor/workerman/workerman/Worker.php(1403): Workerman\Worker::forkWorkersForLinux()
#14 /home/ubuntu/webman/webman/vendor/workerman/workerman/Worker.php(1788): Workerman\Worker::forkWorkers()
#15 /home/ubuntu/webman/webman/vendor/workerman/workerman/Worker.php(1724): Workerman\Worker::monitorWorkersForLinux()
#16 /home/ubuntu/webman/webman/vendor/workerman/workerman/Worker.php(562): Workerman\Worker::monitorWorkers()
#17 /home/ubuntu/webman/webman/vendor/workerman/webman-framework/src/support/App.php(131): Workerman\Worker::runAll()
#18 /home/ubuntu/webman/webman/start.php(4): support\App::run()
#19 {main}
