### ISSUE TITLE
PHP8.3.7 webman1.5.5启动报错

### ISSUE THREAD

**Issue by qinshouwei8816** [walkor/webman#414]
安装webman 1.5.5版本后，php start.php start时 在启动成功时不停的报错
php start.php start
Workerman[start.php] start in DEBUG mode
------------------------------------------- WORKERMAN -------------------------------------------
Workerman version:4.1.15          PHP version:8.3.7           Event-Loop:\Workerman\Events\Event
-------------------------------------------- WORKERS --------------------------------------------
proto   user            worker          listen                 processes    status           
tcp     root            webman          http://0.0.0.0:8787    16            [OK]            
tcp     root            monitor         none                   1             [OK]            
-------------------------------------------------------------------------------------------------
Press Ctrl+C to stop. Start success.
UnexpectedValueException: RecursiveDirectoryIterator::__construct(/webdata/webman/config/static.php): Failed to open directory: Not a directory in /webdata/webman/vendor/workerman/webman-framework/src/Config.php:190
Stack trace:
#0 [internal function]: RecursiveDirectoryIterator->__construct()
#1 /webdata/webman/vendor/workerman/webman-framework/src/Config.php(190): RecursiveDirectoryIterator->getChildren()
#2 /webdata/webman/vendor/workerman/webman-framework/src/Config.php(63): Webman\Config::loadFromDir()
#3 /webdata/webman/vendor/workerman/webman-framework/src/support/App.php(141): Webman\Config::load()
#4 /webdata/webman/support/bootstrap.php(48): support\App::loadAllConfig()
#5 /webdata/webman/vendor/workerman/webman-framework/src/support/App.php(104): require_once('...')
#6 /webdata/webman/vendor/workerman/workerman/Worker.php(2501): support\App::support\{closure}()
#7 /webdata/webman/vendor/workerman/workerman/Worker.php(1636): Workerman\Worker->run()
#8 /webdata/webman/vendor/workerman/workerman/Worker.php(1429): Workerman\Worker::forkOneWorkerForLinux()
#9 /webdata/webman/vendor/workerman/workerman/Worker.php(1403): Workerman\Worker::forkWorkersForLinux()
#10 /webdata/webman/vendor/workerman/workerman/Worker.php(560): Workerman\Worker::forkWorkers()
#11 /webdata/webman/vendor/workerman/webman-framework/src/support/App.php(131): Workerman\Worker::runAll()
#12 /webdata/webman/start.php(4): support\App::run()
#13 {main}
UnexpectedValueException: RecursiveDirectoryIterator::__construct(/webdata/webman/config/static.php): Failed to open directory: Not a directory in /webdata/webman/vendor/workerman/webman-framework/src/Config.php:190
Stack trace:

exit with status 64000
exit with status 64000
exit with status 64000

**Comment by qinshouwei8816** [comment]
已解决，是snow扩展导致的，卸载掉snow即可，php8.3.7支持度很好，感谢walkor
