### ISSUE TITLE
关于初始stdout_file配置的建议

### ISSUE THREAD

**Issue by bigiot** [walkor/webman#5]
初始安装后运行：php start.php start -d
出现如下错误，原因是runtime文件夹下没有log文件夹，无法自动创建stdout.log，所以建议初始配置 config/server.php/stdout_file = runtime_path() . '/stdout.log'，或者runtime文件夹下添加log文件夹，方便初次使用的人运行测试。
```
Fatal error: Uncaught Exception: Can not open stdoutFile /mnt/d/website/webman/runtime/log/stdout.log in /mnt/d/website/webman/vendor/workerman/workerman/Worker.php:1256
Stack trace:
#0 /mnt/d/website/webman/vendor/workerman/workerman/Worker.php(1527): Workerman\Worker::resetStd()
#1 /mnt/d/website/webman/vendor/workerman/workerman/Worker.php(1371): Workerman\Worker::forkOneWorkerForLinux()
#2 /mnt/d/website/webman/vendor/workerman/workerman/Worker.php(1345): Workerman\Worker::forkWorkersForLinux()
#3 /mnt/d/website/webman/vendor/workerman/workerman/Worker.php(546): Workerman\Worker::forkWorkers()
#4 /mnt/d/website/webman/start.php(30): Workerman\Worker::runAll()
#5 {main}
  thrown in /mnt/d/website/webman/vendor/workerman/workerman/Worker.php on line 1256
```

**Comment by yasarluo** [comment]
已修复，参考 #6
