### ISSUE TITLE
能否解释一些一个静态文件的请求过程是怎样的？

### ISSUE THREAD

**Issue by bigtran** [walkor/webman#58]
想请教一下，一个静态文件的请求过程是怎样的？调用了哪些文件？最后返回这个静态文件。

**Comment by walkor** [comment]
1、根据url查找对应文件是否存在，不存在就返回404
2、文件存在则返回文件

```php
#0 /data/project/webman/vendor/workerman/webman-framework/src/App.php(343): Webman\App::send(Object(Workerman\Connection\TcpConnection), Object(Webman\Http\Response), Object(support\Request))
#1 /data/project/webman/vendor/workerman/webman-framework/src/App.php(148): Webman\App::findFile(Object(Workerman\Connection\TcpConnection), '/favicon.ico', 'GET/favicon.ico', Object(support\Request))
#2 /data/project/webman/vendor/workerman/workerman/Connection/TcpConnection.php(660): Webman\App->onMessage(Object(Workerman\Connection\TcpConnection), Object(support\Request))
#3 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #116, 2, Resource id #116)
#4 /data/project/webman/vendor/workerman/workerman/Events/Event.php(195): EventBase->loop()
#5 /data/project/webman/vendor/workerman/workerman/Worker.php(2426): Workerman\Events\Event->loop()
#6 /data/project/webman/vendor/workerman/workerman/Worker.php(1551): Workerman\Worker->run()
#7 /data/project/webman/vendor/workerman/workerman/Worker.php(1381): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
#8 /data/project/webman/vendor/workerman/workerman/Worker.php(1355): Workerman\Worker::forkWorkersForLinux()
#9 /data/project/webman/vendor/workerman/workerman/Worker.php(542): Workerman\Worker::forkWorkers()
#10 /data/project/webman/start.php(146): Workerman\Worker::runAll()
```

**Comment by bigtran** [comment]
了解，多谢

**Comment by walkor** [comment]
不客气
