### ISSUE TITLE
队列怎么用呢？

### ISSUE THREAD

**Issue by yzh52521** [walkor/webman#63]
webman 怎么使用workerman里到那个队列呢？

**Comment by walkor** [comment]
参考手册，需要更新下webman
https://www.workerman.net/doc/webman#/queue/stomp

**Comment by yzh52521** [comment]
> 参考手册，需要更新下webman
> https://www.workerman.net/doc/webman#/queue/stomp

stomp://127.0.0.1:61613
需要开启什么客户端么？
按照手册运行不起来

**Comment by walkor** [comment]
安装个RabbitMQ服务端，并开stomp插件。具体网上搜下文章

**Comment by yzh52521** [comment]
> 安装个RabbitMQ服务端，并开stomp插件。具体网上搜下文章

经常用到到最多是redis或者数据库的队列 能加个最好了

**Comment by walkor** [comment]
其它队列会慢慢加入。其实你可以直接复用composer里的消息队列类库，都是兼容的。

**Comment by walkor** [comment]
https://www.workerman.net/doc/webman#/queue/redis
新增redis队列，欢迎使用。

**Comment by yzh52521** [comment]
> https://www.workerman.net/doc/webman#/queue/redis
> 新增redis队列，欢迎使用。

缺少  Webman\RedisQueue\Process\Consumer 这个类

**Comment by walkor** [comment]
执行 `composer require webman/redis-queue` 安装

**Comment by yzh52521** [comment]
> 执行 `composer require webman/redis-queue` 安装
运行报这个错误
PHP Deprecated:  Non-static method Workerman\RedisQueue\Client::send() should not be called statically in /Applications/MAMP/htdocs/webman/app/controller/Index.php on line 49
PHP Stack trace:
PHP   1. {main}() /Applications/MAMP/htdocs/webman/start.php:0
PHP   2. Workerman\Worker::runAll() /Applications/MAMP/htdocs/webman/start.php:151
PHP   3. Workerman\Worker::forkWorkers() /Applications/MAMP/htdocs/webman/vendor/workerman/workerman/Worker.php:542
PHP   4. Workerman\Worker::forkWorkersForLinux() /Applications/MAMP/htdocs/webman/vendor/workerman/workerman/Worker.php:1359
PHP   5. Workerman\Worker::forkOneWorkerForLinux() /Applications/MAMP/htdocs/webman/vendor/workerman/workerman/Worker.php:1385
PHP   6. Workerman\Worker->run() /Applications/MAMP/htdocs/webman/vendor/workerman/workerman/Worker.php:1555
PHP   7. Workerman\Events\Select->loop() /Applications/MAMP/htdocs/webman/vendor/workerman/workerman/Worker.php:2430
PHP   8. Workerman\Connection\TcpConnection->baseRead() /Applications/MAMP/htdocs/webman/vendor/workerman/workerman/Events/Select.php:293
PHP   9. Webman\App->onMessage() /Applications/MAMP/htdocs/webman/vendor/workerman/workerman/Connection/TcpConnection.php:660
PHP  10. app\controller\Index->queue() /Applications/MAMP/htdocs/webman/vendor/workerman/webman-framework/src/App.php:168

**Comment by walkor** [comment]
按照手册来 使用这个类 `use Webman\RedisQueue\Client;` 不是 `Workerman\RedisQueue\Client`

**Comment by yzh52521** [comment]
好了

**Comment by yzh52521** [comment]
如果消费失败 再push进队列？

**Comment by walkor** [comment]
失败会进入延迟队列，稍后重试，默认重试5次，5次都失败进入失败队列 redis-queue-failed。
重试次数及间隔由 options参数 `max_attempts` 和 `retry_seconds` 控制。

**Comment by yzh52521** [comment]
> 失败会进入延迟队列，稍后重试，默认重试5次，5次都失败进入失败队列 redis-queue-failed。
> 重试次数及间隔由 options参数 `max_attempts` 和 `retry_seconds` 控制。

现在 消费什么也不写 数据就没有了
// 消费
    public function consume($data)
    {
        // 无需反序列化
        var_export($data); // 输出 ['to' => 'tom@gmail.com', 'content' => 'hello']
    }

**Comment by walkor** [comment]
不消费，数据仍然在队列

**Comment by yzh52521** [comment]
> 不消费，数据仍然在队列

刚才试了好几次  队列不在了

**Comment by walkor** [comment]
运行 consume 并且没有抛出异常，就算消费了。

**Comment by yzh52521** [comment]
> 运行 consume 并且没有抛出异常，就算消费了。

哦，比如发短信但是要根据返回值来决定消费是否成功 怎么做？只能再加入队列吧

**Comment by walkor** [comment]
直接抛异常就行了，等它自己重试。

也可以再加队列，不过建议加到延迟队列，并且做个计数，超过一定次数就不要再放队列了，否则搞不好就是无限循环。

**Comment by yzh52521** [comment]
> 直接抛异常就行了，等它自己重试。
> 
> 也可以再加队列，不过建议加到延迟队列，并且做个计数，超过一定次数就不要再放队列了，否则搞不好就是无限循环。

也对 

这样抛异常么？
// 消费
    public function consume($data)
    {
        var_export($data); // 输出 ['to' => 'tom@gmail.com', 'content' => 'hello']
        throw new \Exception('异常消息', 10000);
}
5次后进入了失败队列

{"id":"1603982296.3558.1","time":1603982296,"delay":0,"attempts":6,"queue":"\/topic\/send_mail","data":{"to":"tom@gmail.com","content":"hello"},"error":"Exception: \u5f02\u5e38\u6d88\u606f in \/Applications\/MAMP\/htdocs\/webman\/app\/queue\/redis\/MailSend.php:37\nStack trace:\n#0 \/Applications\/MAMP\/htdocs\/webman\/vendor\/workerman\/redis-queue\/src\/Client.php(195): app\\queue\\redis\\MailSend->consume(Array)\n#1 \/Applications\/MAMP\/htdocs\/webman\/vendor\/workerman\/redis\/src\/Client.php(416): Workerman\\RedisQueue\\Client->Workerman\\RedisQueue\\{closure}(Array, Object(Workerman\\Redis\\Client))\n#2 \/Applications\/MAMP\/htdocs\/webman\/vendor\/workerman\/workerman\/Connection\/TcpConnection.php(660): Workerman\\Redis\\Client->Workerman\\Redis\\{closure}(Object(Workerman\\Connection\\AsyncTcpConnection), Array)\n#3 \/Applications\/MAMP\/htdocs\/webman\/vendor\/workerman\/workerman\/Events\/Select.php(293): Workerman\\Connection\\TcpConnection->baseRead(Resource id #231)\n#4 \/Applications\/MAMP\/htdocs\/webman\/vendor\/workerman\/workerman\/Worker.php(2430): Workerman\\Events\\Select->loop()\n#5 \/Applications\/MAMP\/htdocs\/webman\/vendor\/workerman\/workerman\/Worker.php(1555): Workerman\\Worker->run()\n#6 \/Applications\/MAMP\/htdocs\/webman\/vendor\/workerman\/workerman\/Worker.php(1385): Workerman\\Worker::forkOneWorkerForLinux(Object(Workerman\\Worker))\n#7 \/Applications\/MAMP\/htdocs\/webman\/vendor\/workerman\/workerman\/Worker.php(1359): Workerman\\Worker::forkWorkersForLinux()\n#8 \/Applications\/MAMP\/htdocs\/webman\/vendor\/workerman\/workerman\/Worker.php(1692): Workerman\\Worker::forkWorkers()\n#9 \/Applications\/MAMP\/htdocs\/webman\/vendor\/workerman\/workerman\/Worker.php(1641): Workerman\\Worker::monitorWorkersForLinux()\n#10 \/Applications\/MAMP\/htdocs\/webman\/vendor\/workerman\/workerman\/Worker.php(544): Workerman\\Worker::monitorWorkers()\n#11 \/Applications\/MAMP\/htdocs\/webman\/start.php(151): Workerman\\Worker::runAll()\n#12 {main}"}

**Comment by yzh52521** [comment]
> 直接抛异常就行了，等它自己重试。
> 
> 也可以再加队列，不过建议加到延迟队列，并且做个计数，超过一定次数就不要再放队列了，否则搞不好就是无限循环。

现在失败队列 error 字段只是记录了框架的异常 可不可以记录为什么失败

**Comment by walkor** [comment]
记录的异常就是失败原因

**Comment by dhw-daniel** [comment]
redis 队列支持redis集群么？

**Comment by walkor** [comment]
支持多实例，
```
<?php
return [
    'default' => [
        'host' => 'redis://127.0.0.1:6379',
        'options' => [
            'auth'     => '',   
            'database' => 0,      
            'max_attempts'  => 5, 
            'retry_seconds' => 5, 
         ]
    ],
   'one' => [
        'host' => 'redis://ip:6379',
        'options' => [
            'auth'     => '',     
            'database' => 0,      
            'max_attempts'  => 5, 
            'retry_seconds' => 5, 
         ]
    ],
    'two' => [
        'host' => 'redis://ip:6379',
        'options' => [
            'auth'     => '',     
            'database' => 0,      
            'max_attempts'  => 5, 
            'retry_seconds' => 5, 
         ]
    ],
];
```

然后你可以选择向哪个实例推送。
```
Client::connection('default')->send('/topic/send_mail', [11,22]);
Client::connection('one')->send('/topic/send_mail', [11,22]);
Client::connection('two')->send('/topic/send_mail', [11,22]);
```

**Comment by dhw-daniel** [comment]
redis队列投递成功返回什么数据呢

**Comment by dhw-daniel** [comment]
配置文件支持redis域名设置么

**Comment by dhw-daniel** [comment]
使用集群redis  域名方式连接  控制台提示这个问题，而且队列中也看不到消息

```
Warning: Invalid argument supplied for foreach() in /data/wwwroot/xzzh_tv/vendor/workerman/redis-queue/src/Client.php on line 157
PHP Warning:  Invalid argument supplied for foreach() in /data/wwwroot/xzzh_tv/vendor/workerman/redis-queue/src/Client.php on line 157
```

redis_queue 配置

```
 return [
    'default' => [
        'host' => 'redis://'.env('REDIS_HOST_REB0', 'localhost').':'.env('REDIS_PORT', 6379),
        'options' => [
            'auth'     => env('REDIS_PASSWORD', null),
            'database' => 0,
            'max_attempts'  => env('QUEUE_MAX_ATTEMPTS', 5),
            'retry_seconds' => env('QUEUE_RETRY_SECONDS', 5),
        ]
    ],
    'reb1' => [
        'host' => 'redis://'.env('REDIS_HOST_REB1', 'localhost').':'.env('REDIS_PORT', 6379),
        'options' => [
            'auth'     => env('REDIS_PASSWORD', null),
            'database' => 0,
            'max_attempts'  => env('QUEUE_MAX_ATTEMPTS', 5),
            'retry_seconds' => env('QUEUE_RETRY_SECONDS', 5),
        ]
    ],
    'reb2' => [
        'host' => 'redis://'.env('REDIS_HOST_REB2', 'localhost').':'.env('REDIS_PORT', 6379),
        'options' => [
            'auth'     => env('REDIS_PASSWORD', null),
            'database' => 0,
            'max_attempts'  => env('QUEUE_MAX_ATTEMPTS', 5),
            'retry_seconds' => env('QUEUE_RETRY_SECONDS', 5),
        ]
    ],
    'reb3' => [
        'host' => 'redis://'.env('REDIS_HOST_REB3', 'localhost').':'.env('REDIS_PORT', 6379),
        'options' => [
            'auth'     => env('REDIS_PASSWORD', null),
            'database' => 0,
            'max_attempts'  => env('QUEUE_MAX_ATTEMPTS', 5),
            'retry_seconds' => env('QUEUE_RETRY_SECONDS', 5),
        ]
    ],
    'reb4' => [
        'host' => 'redis://'.env('REDIS_HOST_REB4', 'localhost').':'.env('REDIS_PORT', 6379),
        'options' => [
            'auth'     => env('REDIS_PASSWORD', null),
            'database' => 0,
            'max_attempts'  => env('QUEUE_MAX_ATTEMPTS', 5),
            'retry_seconds' => env('QUEUE_RETRY_SECONDS', 5),
        ]
    ],
    'reb5' => [
        'host' => 'redis://'.env('REDIS_HOST_REB5', 'localhost').':'.env('REDIS_PORT', 6379),
        'options' => [
            'auth'     => env('REDIS_PASSWORD', null),
            'database' => 0,
            'max_attempts'  => env('QUEUE_MAX_ATTEMPTS', 5),
            'retry_seconds' => env('QUEUE_RETRY_SECONDS', 5),
        ]
    ],
];
```

投递消息

```
use Webman\RedisQueue\Client;

    public function send(Request $request)
    {
        // 队列名
        $queue = 'queue:/topic/send_mail';
        // 数据，可以直接传数组，无需序列化
        $data = ['to' => 'tom@gmail.com', 'content' => 'hello'];
        // 投递消息
        //Client::send($queue, $data);
        // 投递延迟消息，消息会在60秒后处理
        $tmp = Client::connection('reb5')->send($queue, $data);
        var_dump($tmp);
    }
```

**Comment by lxmwuchao1314** [comment]
按照手册队列投递成功，消费时没有任何输出，还需要执行什么吗？

**Comment by lxmwuchao1314** [comment]
> 运行 consume 并且没有抛出异常，就算消费了。

怎么执行这个呢，我看到redis有队列，但是消费没有执行，

**Comment by walkor** [comment]
https://www.workerman.net/doc/webman#/queue/redis?id=%e6%b6%88%e8%b4%b9%e6%b6%88%e6%81%af
