### ISSUE TITLE
vlucas/phpdotenv vs illumiate conflict after redis support added

### ISSUE THREAD

**Issue by latypoff** [walkor/webman#70]
```
# php -v
PHP 7.2.24-0ubuntu0.18.04.7 (cli) (built: Oct  7 2020 15:24:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.7, Copyright (c) 1999-2018, by Zend Technologies

# git clone https://github.com/walkor/webman
# composer install
# composer require illuminate/redis
# php ./start.php
PHP Fatal error:  Uncaught Error: Call to private Dotenv\Repository\Adapter\EnvConstAdapter::__construct() from context 'Illuminate\Support\Env' in /root/webman/vendor/illuminate/support/Env.php:58
Stack trace:
#0 /root/webman/vendor/illuminate/support/Env.php(81): Illuminate\Support\Env::getRepository()
#1 /root/webman/vendor/illuminate/support/helpers.php(276): Illuminate\Support\Env::get('APP_DEBUG', false)
#2 /root/webman/config/app.php(16): env('APP_DEBUG', false)
#3 /root/webman/vendor/workerman/webman-framework/src/Config.php(36): include('/root/webman/co...')
#4 /root/webman/start.php(23): Webman\Config::load('/root/webman/co...', Array)
#5 {main}
  thrown in /root/webman/vendor/illuminate/support/Env.php on line 58
```

**Comment by walkor** [comment]
Try to run command `composer require vlucas/phpdotenv ^5.1.0` .

**Comment by latypoff** [comment]
> Try to run command `composer require vlucas/phpdotenv ^5.1.0` .

```
# composer require vlucas/phpdotenv ^5.1.0
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Warning from https://packagist.org: You are using an outdated version of Composer. Composer 2.0 is now available and you should upgrade. See https://getcomposer.org/2
./composer.json has been updated
Loading composer repositories with package information
Warning from https://packagist.org: You are using an outdated version of Composer. Composer 2.0 is now available and you should upgrade. See https://getcomposer.org/2
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
> @php -r "file_exists('.env') || copy('.env.example', '.env');"

# php ./start.php
PHP Fatal error:  Uncaught Error: Call to private Dotenv\Repository\Adapter\EnvConstAdapter::__construct() from context 'Illuminate\Support\Env' in /root/webman/vendor/illuminate/support/Env.php:58
Stack trace:
#0 /root/webman/vendor/illuminate/support/Env.php(81): Illuminate\Support\Env::getRepository()
#1 /root/webman/vendor/illuminate/support/helpers.php(276): Illuminate\Support\Env::get('APP_DEBUG', false)
#2 /root/webman/config/app.php(16): env('APP_DEBUG', false)
#3 /root/webman/vendor/workerman/webman-framework/src/Config.php(36): include('/root/webman/co...')
#4 /root/webman/start.php(23): Webman\Config::load('/root/webman/co...', Array)
#5 {main}
  thrown in /root/webman/vendor/illuminate/support/Env.php on line 58
```

**Comment by walkor** [comment]
```
composer require illuminate/redis ^8.2.0
```

**Comment by latypoff** [comment]
> ```
> composer require illuminate/redis ^8.2.0
> ```

`Package illuminate/redis at version ^8.2.0 has a PHP requirement incompatible with your PHP version (7.2.24)`

**Comment by walkor** [comment]
if your php < 7.3 use the follow commands.
```
composer require vlucas/phpdotenv ^4.0
composer require illuminate/redis ^7.0
```
else use these commands.
```
composer require vlucas/phpdotenv ^5.0
composer require illuminate/redis ^8.0
```

**Comment by latypoff** [comment]
Thanks!

`composer require vlucas/phpdotenv ^4.0`

did the trick!

**Comment by peinhu** [comment]
同遇到这个问题，为了弄清哪个版本的phpdotenv能用，还去看了半天源码。。。最后发现phpdotenv的4.1.0版本是那个方法修改前的最后一个版本，再高就会报错了，遇到这个问题的装4.1.0就行了
