### ISSUE TITLE
After one month I put webman application on production server, its suddently stop

### ISSUE THREAD

**Issue by haidarvm** [walkor/webman#83]
I got many times, webman service stop for unknown reason and here's the last log
```
[2020-11-21 00:21:14] default.ERROR: Trying to access array offset on value of type null {"exception":"ErrorException: Trying to access array offset on value of type null in /home/client/kitabemas/vendor/workerman/webman-framework/src/App.php:399
Stack trace:
#0 /home/client/kitabemas/vendor/workerman/webman-framework/src/App.php(399): {closure}()
#1 /home/client/kitabemas/vendor/workerman/webman-framework/src/App.php(152): Webman\\App::parseControllerAction()
#2 /home/client/kitabemas/vendor/workerman/workerman/Connection/TcpConnection.php(660): Webman\\App->onMessage()
#3 /home/client/kitabemas/vendor/workerman/workerman/Events/Select.php(293): Workerman\\Connection\\TcpConnection->baseRead()
#4 /home/client/kitabemas/vendor/workerman/workerman/Worker.php(2430): Workerman\\Events\\Select->loop()
#5 /home/client/kitabemas/vendor/workerman/workerman/Worker.php(1555): Workerman\\Worker->run()
#6 /home/client/kitabemas/vendor/workerman/workerman/Worker.php(1385): Workerman\\Worker::forkOneWorkerForLinux()
#7 /home/client/kitabemas/vendor/workerman/workerman/Worker.php(1359): Workerman\\Worker::forkWorkersForLinux()
#8 /home/client/kitabemas/vendor/workerman/workerman/Worker.php(542): Workerman\\Worker::forkWorkers()
#9 /home/client/kitabemas/start.php(156): Workerman\\Worker::runAll()
#10 {main}"} []
```
and here's what happen if user_id session empty / reset. I still can't find the issue why session user_id is gone

```
Next Illuminate\\Database\\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'post_author' cannot be null (SQL: insert into `wprg_posts` (`post_status`, `post_type`, `post_author`, `post_date`) values (draft, post, ?, 2020-11-24 22:11:52)) in /home/client/roemahmedia/public_html/vendor/illuminate/database/Connection.php:671
Stack trace:
#0 /home/client/roemahmedia/public_html/vendor/illuminate/database/Connection.php(631): Illuminate\\Database\\Connection->runQueryCallback()
#1 /home/client/roemahmedia/public_html/vendor/illuminate/database/Connection.php(465): Illuminate\\Database\\Connection->run()
#2 /home/client/roemahmedia/public_html/vendor/illuminate/database/Connection.php(417): Illuminate\\Database\\Connection->statement()
#3 /home/client/roemahmedia/public_html/vendor/illuminate/database/Query/Processors/Processor.php(32): Illuminate\\Database\\Connection->insert()
#4 /home/client/roemahmedia/public_html/vendor/illuminate/database/Query/Builder.php(2872): Illuminate\\Database\\Query\\Processors\\Processor->processInsertGetId()
#5 /home/client/roemahmedia/public_html/vendor/illuminate/database/Eloquent/Builder.php(1508): Illuminate\\Database\\Query\\Builder->insertGetId()
#6 /home/client/roemahmedia/public_html/vendor/illuminate/support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->__call()
#7 /home/client/roemahmedia/public_html/vendor/illuminate/database/Eloquent/Model.php(1884): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#8 /home/client/roemahmedia/public_html/app/admin/model/AdminModel.php(227): Illuminate\\Database\\Eloquent\\Model->__call()
#9 /home/client/roemahmedia/public_html/app/admin/controller/posts.php(59): app\\admin\\model\\AdminModel->newPost()
#10 /home/client/roemahmedia/public_html/vendor/workerman/webman-framework/src/App.php(140): app\\admin\\controller\\Posts->add_post()
#11 /home/client/roemahmedia/public_html/vendor/workerman/workerman/Connection/TcpConnection.php(660): Webman\\App->onMessage()
#12 /home/client/roemahmedia/public_html/vendor/workerman/workerman/Events/Select.php(293): Workerman\\Connection\\TcpConnection->baseRead()
#13 /home/client/roemahmedia/public_html/vendor/workerman/workerman/Worker.php(2430): Workerman\\Events\\Select->loop()
#14 /home/client/roemahmedia/public_html/vendor/workerman/workerman/Worker.php(1555): Workerman\\Worker->run()
#15 /home/client/roemahmedia/public_html/vendor/workerman/workerman/Worker.php(1385): Workerman\\Worker::forkOneWorkerForLinux()
#16 /home/client/roemahmedia/public_html/vendor/workerman/workerman/Worker.php(1359): Workerman\\Worker::forkWorkersForLinux()
#17 /home/client/roemahmedia/public_html/vendor/workerman/workerman/Worker.php(542): Workerman\\Worker::forkWorkers()
#18 /home/client/roemahmedia/public_html/start.php(138): Workerman\\Worker::runAll()
#19 {main}"} []
```

I did use webman with nohup, it should be always start, but why it's stop many times, sometime in 3 days or less the webman service is stop

**Comment by walkor** [comment]
Start webman with daemon mode the command is `php start.php start -d`, `-d` is the key. nohup is not necessary.

**Comment by haidarvm** [comment]
> Start webman with daemon mode the command is `php start.php start -d`, `-d` is the key. nohup is not necessary.

i did use php start.php restart -d
```
#!/bin/bash
php start.php restart -d
```

is it same for daemon ?

**Comment by walkor** [comment]
> is it same for daemon ?

Yes.

**Comment by walkor** [comment]
How do you know that webman is stopped? Use a command like `ps aux`?

**Comment by haidarvm** [comment]
> How do you know that webman is stopped? Use a command like `ps aux`?

I'm using nginx proxy so it's just said 504 Bad Gateway

**Comment by walkor** [comment]
Please use command `ps auxf` to see if the webman process exist when got `504 Bad Gateway`.
If the webman process exist then run command `php start.php status` and show the output.
Please upload `vendor/workerman/workerman.log `.

**Comment by haidarvm** [comment]
ok, i'll wait next time maybe tomorrow it's gonna stop again. Usually I did before using ps aux | grep webman is gone

**Comment by haidarvm** [comment]
```
[client@haidarvm ~]$ ps aux | grep webman
client      7405  0.0  0.0 221900  1056 pts/0    S+   09:56   0:00 grep --color=auto webman
[client@haidarvm ~]$ cd roemahmedia/public_html/
[client@haidarvm public_html]$ ls
app            config   logs       public      runtime    stop.sh
composer.json  db       nohup.out  README.md   start.php  support
composer.lock  LICENSE  process    restart.sh  start.sh   vendor
[client@haidarvm public_html]$ php start.php status
Workerman[start.php] status 
Workerman[start.php] not run
[client@haidarvm public_html]$ cd /home/client/kitabemas/
[client@haidarvm kitabemas]$ php start.php status
Workerman[start.php] status 
Workerman[start.php] not run
```

Why the webman die both on same server ?
please My client complain about it

**Comment by walkor** [comment]
Run command `top` and show the top 5 lines line which something like `top - 11:03:53 up 441 days, 13:20,  1 user,  load average: 0.00, 0.05, 0.06 ....`.
Run command `php start.php status` and show the output.
Upload your `vendor/workerman/workerman.log` here.
Check system log (something like `/var/log/kern.log` `/var/log/messages`) to see if there are any error logs.
Run command `dmesg` to see if there are any error logs.

**Comment by haidarvm** [comment]
> Run command `top` and show the top 5 lines line which something like `top - 11:03:53 up 441 days, 13:20, 1 user, load average: 0.00, 0.05, 0.06 ....`.
> Run command `php start.php status` and show the output.
> Upload your `vendor/workerman/workerman.log` here.
> Check system log (something like `/var/log/kern.log` `/var/log/messages`) to see if there are any error logs.
> Run command `dmesg` to see if there are any error logs.

Ok later i'll do again when webman stop again

**Comment by walkor** [comment]
You can do that now.

**Comment by haidarvm** [comment]
> .

Ok I'll do it now

**Comment by haidarvm** [comment]
```
Workerman[start.php] status 
----------------------------------------------GLOBAL STATUS----------------------------------------------------
Workerman version:4.0.16          PHP version:7.4.13
start time:2020-12-03 10:59:08   run 3 days 10 hours   
load average: 0.09, 0, 0         event-loop:\Workerman\Events\Select
2 workers       3 processes
worker_name  exit_status      exit_count
webman       0                0
monitor      0                0
----------------------------------------------PROCESS STATUS---------------------------------------------------
pid	memory  listening                   worker_name  connections send_fail timers  total_request qps    status
7492	6M      http://roemahmedia.com:8181 webman       1           2         0       484           0      [idle]
7493	6M      http://roemahmedia.com:8181 webman       1           0         0       512           0      [idle]
7494	2M      none                        monitor      0           0         0       0             0      [idle]
----------------------------------------------PROCESS STATUS---------------------------------------------------
Summary	14M     -                           -            2           2         0       996           0      [Summary] 
```
vendor/workerman/workerman.log
```
2020-11-18 09:14:34 pid:36658 Workerman[start.php] stopping ...
2020-11-18 09:14:34 pid:36658 Workerman[start.php] has been stopped
2020-11-18 09:14:34 pid:36864 Workerman[start.php] stop success
2020-11-24 07:41:23 pid:36867 Workerman[start.php] stopping ...
2020-11-24 07:41:23 pid:36867 Workerman[start.php] stopping ...
2020-11-24 07:41:23 pid:36867 Workerman[start.php] has been stopped
2020-11-24 10:43:08 pid:6384 Workerman[start.php] restart 
2020-11-24 10:43:08 pid:6384 Workerman[start.php] is stopping ...
2020-11-24 10:43:08 pid:6384 Workerman[start.php] stop success
2020-11-25 07:24:33 pid:6387 Workerman[start.php] stopping ...
2020-11-25 07:24:33 pid:6387 Workerman[start.php] stopping ...
2020-11-25 07:24:33 pid:6387 Workerman[start.php] has been stopped
2020-11-25 08:27:55 pid:3068 Workerman[start.php] restart 
2020-11-25 08:27:55 pid:3068 Workerman[start.php] is stopping ...
2020-11-25 08:27:55 pid:3068 Workerman[start.php] stop success
2020-11-25 08:31:00 pid:3225 Workerman[start.php] restart 
2020-11-25 08:31:00 pid:3225 Workerman[start.php] is stopping ...
2020-11-25 08:31:00 pid:3071 Workerman[start.php] stopping ...
2020-11-25 08:31:00 pid:3071 Workerman[start.php] has been stopped
2020-11-25 08:31:00 pid:3225 Workerman[start.php] stop success
2020-11-30 03:52:40 pid:212295 Workerman[start.php] restart 
2020-11-30 03:52:40 pid:212295 Workerman[start.php] is stopping ...
2020-11-30 03:52:40 pid:3228 Workerman[start.php] stopping ...
2020-11-30 03:52:40 pid:3228 Workerman[start.php] has been stopped
2020-11-30 03:52:40 pid:212295 Workerman[start.php] stop success
2020-12-03 07:38:53 pid:212298 Workerman[start.php] stopping ...
2020-12-03 07:38:53 pid:212298 Workerman[start.php] stopping ...
2020-12-03 07:38:53 pid:212298 Workerman[start.php] has been stopped
2020-12-03 10:57:07 pid:7429 Workerman[start.php] status 
2020-12-03 10:57:07 pid:7429 Workerman[start.php] not run
2020-12-03 10:59:08 pid:7488 Workerman[start.php] start in DAEMON mode
2020-12-06 21:55:42 pid:156878 Workerman[start.php] status 
```
/var/log/messages
```
Dec  6 20:56:01 haidarvm systemd[1]: Stopped User Manager for UID 0.
Dec  6 20:56:01 haidarvm systemd[1]: user-runtime-dir@0.service: Unit not needed anymore. Stopping.
Dec  6 20:56:01 haidarvm systemd[1]: Removed slice User Slice of UID 0.
Dec  6 20:56:01 haidarvm systemd[1]: Stopping /run/user/0 mount wrapper...
Dec  6 20:56:01 haidarvm systemd[1]: Stopped /run/user/0 mount wrapper.
Dec  6 20:56:04 haidarvm dbus-daemon[568]: [system] Activating service name='org.fedoraproject.Setroubleshootd' requested by ':1.47' (uid=0 pid=525 comm="/usr/sbin/sedispatch " label="system_u:system_r:auditd_t:s0") (using servicehelper)
Dec  6 20:56:04 haidarvm dbus-daemon[156911]: [system] Failed to reset fd limit before activating service: org.freedesktop.DBus.Error.AccessDenied: Failed to restore old fd limit: Operation not permitted
Dec  6 20:56:05 haidarvm dbus-daemon[568]: [system] Successfully activated service 'org.fedoraproject.Setroubleshootd'
Dec  6 20:56:07 haidarvm setroubleshoot[156911]: SELinux is preventing local from create access on the file 1607262961.P156909.haidarvm.com. For complete SELinux messages run: sealert -l 6964ab20-39bf-4633-8a7c-48879842665f
Dec  6 20:56:07 haidarvm platform-python[156911]: SELinux is preventing local from create access on the file 1607262961.P156909.haidarvm.com.#012#012*****  Plugin catchall (100. confidence) suggests   **************************#012#012If you believe that local should be allowed create access on the 1607262961.P156909.haidarvm.com file by default.#012Then you should report this as a bug.#012You can generate a local policy module to allow this access.#012Do#012allow this access for now by executing:#012# ausearch -c 'local' --raw | audit2allow -M my-local#012# semodule -X 300 -i my-local.pp#012
Dec  6 20:56:07 haidarvm setroubleshoot[156911]: SELinux is preventing local from create access on the file 1607262961.P156909.haidarvm.com. For complete SELinux messages run: sealert -l 6964ab20-39bf-4633-8a7c-48879842665f
Dec  6 20:56:07 haidarvm platform-python[156911]: SELinux is preventing local from create access on the file 1607262961.P156909.haidarvm.com.#012#012*****  Plugin catchall (100. confidence) suggests   **************************#012#012If you believe that local should be allowed create access on the 1607262961.P156909.haidarvm.com file by default.#012Then you should report this as a bug.#012You can generate a local policy module to allow this access.#012Do#012allow this access for now by executing:#012# ausearch -c 'local' --raw | audit2allow -M my-local#012# semodule -X 300 -i my-local.pp#012
Dec  6 20:56:08 haidarvm setroubleshoot[156911]: SELinux is preventing local from getattr access on the file /root/Maildir/tmp/1607262961.P156909.haidarvm.com. For complete SELinux messages run: sealert -l 2909b8f7-ed67-4275-8527-a530194a489d
Dec  6 20:56:08 haidarvm platform-python[156911]: SELinux is preventing local from getattr access on the file /root/Maildir/tmp/1607262961.P156909.haidarvm.com.#012#012*****  Plugin restorecon (99.5 confidence) suggests   ************************#012#012If you want to fix the label. #012/root/Maildir/tmp/1607262961.P156909.haidarvm.com default label should be mail_home_rw_t.#012Then you can run restorecon. The access attempt may have been stopped due to insufficient permissions to access a parent directory in which case try to change the following command accordingly.#012Do#012# /sbin/restorecon -v /root/Maildir/tmp/1607262961.P156909.haidarvm.com#012#012*****  Plugin catchall (1.49 confidence) suggests   **************************#012#012If you believe that local should be allowed getattr access on the 1607262961.P156909.haidarvm.com file by default.#012Then you should report this as a bug.#012You can generate a local policy module to allow this access.#012Do#012allow this access for now by executing:#012# ausearch -c 'local' --raw | audit2allow -M my-local#012# semodule -X 300 -i my-local.pp#012
Dec  6 20:56:09 haidarvm setroubleshoot[156911]: SELinux is preventing local from read access on the file 1607262961.P156909.haidarvm.com. For complete SELinux messages run: sealert -l 9b96b297-0b8b-49fe-ae47-6d7a0bd51f01
Dec  6 20:56:09 haidarvm platform-python[156911]: SELinux is preventing local from read access on the file 1607262961.P156909.haidarvm.com.#012#012*****  Plugin catchall (100. confidence) suggests   **************************#012#012If you believe that local should be allowed read access on the 1607262961.P156909.haidarvm.com file by default.#012Then you should report this as a bug.#012You can generate a local policy module to allow this access.#012Do#012allow this access for now by executing:#012# ausearch -c 'local' --raw | audit2allow -M my-local#012# semodule -X 300 -i my-local.pp#012
Dec  6 20:56:10 haidarvm setroubleshoot[156911]: SELinux is preventing local from read access on the file 1607262961.P156909.haidarvm.com. For complete SELinux messages run: sealert -l 9b96b297-0b8b-49fe-ae47-6d7a0bd51f01
Dec  6 20:56:10 haidarvm platform-python[156911]: SELinux is preventing local from read access on the file 1607262961.P156909.haidarvm.com.#012#012*****  Plugin catchall (100. confidence) suggests   **************************#012#012If you believe that local should be allowed read access on the 1607262961.P156909.haidarvm.com file by default.#012Then you should report this as a bug.#012You can generate a local policy module to allow this access.#012Do#012allow this access for now by executing:#012# ausearch -c 'local' --raw | audit2allow -M my-local#012# semodule -X 300 -i my-local.pp#012
Dec  6 20:56:10 haidarvm setroubleshoot[156911]: SELinux is preventing local from unlink access on the file 1607262961.P156909.haidarvm.com. For complete SELinux messages run: sealert -l 15b98714-be03-48ab-ab62-fb7101f8b77e
Dec  6 20:56:10 haidarvm platform-python[156911]: SELinux is preventing local from unlink access on the file 1607262961.P156909.haidarvm.com.#012#012*****  Plugin catchall (100. confidence) suggests   **************************#012#012If you believe that local should be allowed unlink access on the 1607262961.P156909.haidarvm.com file by default.#012Then you should report this as a bug.#012You can generate a local policy module to allow this access.#012Do#012allow this access for now by executing:#012# ausearch -c 'local' --raw | audit2allow -M my-local#012# semodule -X 300 -i my-local.pp#012
Dec  6 20:57:49 haidarvm systemd-logind[653]: Session 2594 logged out. Waiting for processes to exit.
Dec  6 20:57:49 haidarvm systemd-logind[653]: Removed session 2594.
Dec  6 20:58:15 haidarvm systemd[1]: Created slice User Slice of UID 1000.
Dec  6 20:58:15 haidarvm systemd[1]: Started /run/user/1000 mount wrapper.
Dec  6 20:58:15 haidarvm systemd[1]: Starting User Manager for UID 1000...
Dec  6 20:58:15 haidarvm systemd[1]: Started Session 2597 of user haidarvm.
Dec  6 20:58:15 haidarvm systemd-logind[653]: New session 2597 of user haidarvm.
Dec  6 20:58:15 haidarvm systemd[156993]: Reached target Paths.
Dec  6 20:58:15 haidarvm systemd[156993]: Started Mark boot as successful after the user session has run 2 minutes.
Dec  6 20:58:15 haidarvm systemd[156993]: Reached target Timers.
Dec  6 20:58:15 haidarvm systemd[156993]: Starting D-Bus User Message Bus Socket.
Dec  6 20:58:15 haidarvm systemd[156993]: Listening on D-Bus User Message Bus Socket.
Dec  6 20:58:15 haidarvm systemd[156993]: Reached target Sockets.
Dec  6 20:58:15 haidarvm systemd[156993]: Reached target Basic System.
Dec  6 20:58:15 haidarvm systemd[156993]: Reached target Default.
Dec  6 20:58:15 haidarvm systemd[156993]: Startup finished in 26ms.
Dec  6 20:58:15 haidarvm systemd[1]: Started User Manager for UID 1000.
```

**Comment by walkor** [comment]
Please run command top and show the top 5 lines line which something like top - 11:03:53 up 441 days, 13:20, 1 user, load average: 0.00, 0.05, 0.06 ....

**Comment by haidarvm** [comment]
> Please run command top and show the top 5 lines line which something like top - 11:03:53 up 441 days, 13:20, 1 user, load average: 0.00, 0.05, 0.06 ....

Could you give the correct ```top``` command

**Comment by walkor** [comment]
Just run top.

**Comment by haidarvm** [comment]
NO, now its die again

**Comment by walkor** [comment]
Run command `top` and show the output.
Upload your vendor/workerman/workerman.log here.
Check system log (something like `/var/log/kern.log` `/var/log/messages`) to see if there are any error logs.
Run command `dmesg` to see if there are any error logs.

**Comment by haidarvm** [comment]
php -v
```
[root@haidarvm ~]# php -v
PHP 7.4.13 (cli) (built: Nov 24 2020 10:03:34) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
```

**Comment by walkor** [comment]
It looks like your system has been rebooted so webman process died.

**Comment by haidarvm** [comment]
Damn, you correct, so i have to run it on startup ?

**Comment by walkor** [comment]
Yes.

**Comment by haidarvm** [comment]
> Yes.

how to run it on startup on centos / rhel ?

**Comment by walkor** [comment]
Add start command to `/etc/rc.local`.
For example.
```
/usr/bin/env php /your/path/of/webman/start.php start -d

exit 0
```

**Comment by haidarvm** [comment]
> Add start command to `/etc/rc.local`.
> For example.
> 
> ```
> /usr/bin/env php /your/path/of/webman/start.php start -d
> 
> exit 0
> ```

Ok Done, thanks alot
